---

# Vault Password - Master Ansible Vault password used to encrypt all of the following variables. 
# Please store this password securely for future use as it does not persist after project execution.

vault_password: <CHANGEME>

# AWS_credentials

aws_credentials_list:
  - dummy

dummy_access_key_id: <CHANGEME>
dummy_secret_access_key: <CHANGEME>

# cluster.yml

cluster_credential_git_repo: <CHANGEME>

cluster_pod_openshift_user: <CHANGEME>
cluster_pod_openshift_pass: <CHANGEME>

cluster_credential_bundle_aws_name: <CHANGEME>

cluster_type: <CHANGEME> #set to 'dev' or 'poc'

rh_user: <CHANGEME>
rh_pass: <CHANGEME>

dev_domain: <CHANGEME>
poc_domain: <CHANGEME>

htpasswd_username: <CHANGEME>
htpasswd_password: <CHANGEME>

# integreatly_vault.yml

tower_credential_bundle_vault_name: <CHANGEME>
integreatly_vault: <CHANGEME>

# letsencrypt.yml

letsencrypt_private_key:
    -----BEGIN RSA PRIVATE KEY-----
    <CHANGEME>
    -----END RSA PRIVATE KEY-----

# tower_github_authentication.yml

social_auth_github_org_name: <CHANGEME>
social_auth_github_org_key: <CHANGEME>
social_auth_github_org_secret: <CHANGEME>
  
social_auth_github_org_organization_map: "{'<CHANGEME>': {'admins': True, 'users': True}}"
social_auth_github_org_team_map: "{'<CHANGEME>': {'organization': '<CHANGEME>', 'users': True}}"

# tower_github_scm.yml

tower_github_scm_password: <CHANGEME>
tower_github_scm:
    -----BEGIN RSA PRIVATE KEY-----
    <CHANGEME>
    -----END RSA PRIVATE KEY-----

# tower_openshift_authentication.yml

tower_openshift_username: <CHANGEME> 
tower_openshift_password: <CHANGEME>
tower_openshift_master_url: <CHANGEME>

# tower_ssh.yml

tower_ssh_user: <CHANGEME>
tower_ssh:
    -----BEGIN RSA PRIVATE KEY-----
    <CHANGEME>
    -----END RSA PRIVATE KEY-----

# tower_credentials

tower_instance_list:
  - dummy

dummy_tower_host: <CHANGEME>
dummy_tower_verify_ssl: True
dummy_tower_username: <CHANGEME>
dummy_tower_password: <CHANGEME>