cluster_credential_git_user: 'awx'
cluster_credential_git_user_group: 'awx'
cluster_credential_git_repo: 'https://github.com/integr8ly/tower_dummy_credentials'
cluster_credential_git_ref: 'master'

cluster_pod_openshift_user: ''
cluster_pod_openshift_pass: ''

cluster_credential_bundle_aws_name: ''

rh_pool: ''

rh_user: ''
  
rh_pass: ''

dev_domain: ''
poc_domain: ''

htpasswd_username: ''
htpasswd_password: ''

cluster_master: "{{ groups['oo_master_primary'] | intersect(groups['oo_clusterid_' ~ oo_clusterid]) | first }}"
g_inventory_cloud_provider: "{{ oo_sublocation }}"
cli_containerized: False
scf_retval_openshift_cert: "/tmp/{{ oo_clusterid }}/certs/wildcard.{{ oo_clusterid }}.{{ domain }}.crt"
scf_retval_chain_cert: "/tmp/{{ oo_clusterid }}/certs/rootCA.pem"
scf_retval_openshift_key: "/tmp/{{ oo_clusterid }}/certs/wildcard.{{ oo_clusterid }}.{{ domain }}.key"
certfile: "{{ scf_retval_openshift_cert }}"
scf_retval_router_cert: "/tmp/{{ oo_clusterid }}/certs/wildcard.apps.{{ oo_clusterid }}.{{ domain }}.crt"
scr_retval_router_key: "/tmp/{{ oo_clusterid }}/certs/wildcard.apps.{{ oo_clusterid }}.{{ domain }}.key"
g_play_dns_role_path: "/tmp/oa_dns_hook"

# Instance Sizes #
master_instance_size: m4.xlarge
compute_instance_size: m4.xlarge
infra_instance_size: m4.xlarge

# Instance Counts #
openshift_aws_compute_group_desired_size: 3
openshift_aws_infra_group_desired_size: 3
openshift_aws_master_group_desired_size: 3

# Flags #
flag_provision_dns: true
flag_provision_metrics: true

# Common Vars #
oa_vpc_cidr: 172.31.0.0/16
operator_lifecycle_manager_install: false
g_enable_config_loop: false
g_enable_monitoring: false
g_run_config_loop: false
