---
- name: Applying templates
  template:
    src: "{{ item }}"
    dest: "inventories/group_vars/all/{{ item | basename | regex_replace('.j2','') }}"
  with_fileglob:
    -  templates/*.yml.j2
  register: var